---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: elk-stack  # 원하는 네임스페이스로 변경 가능
  labels:
    app: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin:latest
        ports:
        - containerPort: 9411
        env:
        - name: STORAGE_TYPE
          value: elasticsearch
        - name: ES_HOSTS
          value: https://elasticsearch-master.elk-stack.svc:9200  # HTTPS 프로토콜 사용
        # Elasticsearch 인증 정보 설정
        - name: ES_USERNAME
          valueFrom:
            secretKeyRef:
              name: elasticsearch-master-credentials  # 시크릿 이름 변경
              key: username
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-master-credentials  # 시크릿 이름 변경
              key: password
        - name: JAVA_OPTS
          value: >
            -Djavax.net.ssl.trustStore=/etc/zipkin-certs/truststore.p12
            -Djavax.net.ssl.trustStorePassword=Qhdks100%
            -Djavax.net.ssl.trustStoreType=PKCS12
        volumeMounts:
        - name: zipkin-truststore
          mountPath: /etc/zipkin-certs
          readOnly: true
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
      volumes:
      - name: zipkin-truststore
        secret:
          secretName: zipkin-truststore
          items:
          - key: truststore.p12
            path: truststore.p12
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: elk-stack  
  labels:
    app: zipkin
spec:
  type: NodePort 
  ports:
  - port: 9411
    targetPort: 9411
    protocol: TCP
    name: http
  selector:
    app: zipkin
