apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-data-1
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-server
  nfs:
    path: /home/data/elastic-data-1
    server: 125.6.36.105
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-data-2
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-server
  nfs:
    path: /home/data/elastic-data-2
    server: 125.6.36.105
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-data-3
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-server
  nfs:
    path: /home/data/elastic-data-3
    server: 125.6.36.105
