# ex) pv.yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: good-pv-0
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce #ReadWriteMany #ReadWriteOnce #ReadOnlyMany #ReadWriteOncePod ( 1.29 이상 적용)
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-server
  nfs:
    path:   /data/worker0
    server: 133.186.228.20
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
          - key: app     
            operator: In
            values: 
            - ms